# Generated by Django 4.1.3 on 2022-12-01 03:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first_App', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, unique=True)),
                ('number_of_employees', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='accessrecord',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='accessrecord',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(max_length=264, unique=True)),
                ('date_of_birth', models.DateField(default=datetime.date.today)),
                ('company_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='first_App.company')),
            ],
        ),
    ]
